language: node_js
node_js:
  - lts/*
cache: npm
script:
  - npm run deploy
deploy:
  provider: pages
  local_dir: build
  skip_cleanup: true
  github_token: 08bc3329d4e7f39ce548aa9415eb3af6185b80b4  # Set in the settings page of your repository, as a secure variable
